---
# tasks file for collectconfig
- block:
  - name: "collect file [{{ collect_file }}]"
    fetch:
      src: "{{ collect_file }}"
      dest: "{{ output }}/{{ collect_datetime }}/{{ ansible_hostname }}"

  when: >
    collect_file != None
