---
# tasks file for collectconfig
- name: exec sosreport
  shell: "{{ sosreport_prefix }} /sbin/sosreport {{ sosreport_option }}|/bin/grep '/var/tmp/sosreport-'| /bin/sed 's/^ *//'"
  register: sosreport_result
  become: "{{ become_enabled }}"

- name: add read permission
  file:
    path: "{{ sosreport_result.stdout }}"
    mode: 0644
  become: "{{ become_enabled }}"
  when: become_enabled

- name: collect sosreport
  fetch:
    src: "{{ sosreport_result.stdout }}"
    dest: "{{ output }}/{{ collect_datetime }}/{{ ansible_hostname }}/{{ item }}"
    flat: true
  with_items:
    - "{{ sosreport_result.stdout }}"
    - "{{ sosreport_result.stdout }}.md5"
  become: false

- name: delete sosreport
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ sosreport_result.stdout }}"
    - "{{ sosreport_result.stdout }}.md5"
  become: "{{ become_enabled }}"
  when: sosreport_delete
