---
# tasks file for collectconfig
- name: set collect datetime
  set_fact: collect_datetime="{{ ansible_date_time.date|regex_replace('-', '') }}{{ ansible_date_time.time|regex_replace(':', '') }}"
  run_once: true

- name: collect files
  include_tasks: collectfile.yml
  with_items:
    "{{ collect_files }}"
  loop_control:
    loop_var: collect_file

- name: collect cli
  include_tasks: collectcli.yml
  with_items:
    "{{ collect_cli_commands }}"
  loop_control:
    loop_var: collect_cli
