---
# tasks file for collectconfig
- name: set collect datetime
  set_fact: collect_datetime="{{ ansible_date_time.date|regex_replace('-', '') }}{{ ansible_date_time.time|regex_replace(':', '') }}"
  run_once: true

- name: "create output dir"
  local_action:
    module: file
    path: "{{ output }}/{{ collect_datetime }}/{{ ansible_hostname }}"
    state: directory
  become: false
  when: >
    collect_files != None or
    collect_cli_commands != None

- name: collect permission
  include_tasks: collectpermission.yml

- name: collect files
  include_tasks: collectfile.yml
  with_items:
    "{{ collect_files }}"
  loop_control:
    loop_var: collect_file

- name: collect cli
  include_tasks: collectcli.yml
  with_items:
    "{{ collect_cli_commands }}"
  loop_control:
    loop_var: collect_cli

- name: collect sosreport
  include_tasks: collectsosreport.yml
  when: collect_sosreport

- name: compress collect data
  include_tasks: compresscollectdata.yml
  when: compress_collect_data
