---
# defaults file for collectconfig
proxy_env:
  no_proxy: '*'
#  http_proxy: http://172.16.111.1:8080
#  https_proxy: http://172.16.111.1:8080
become_enabled: false
gateway_address: 'xxx.xxx.xxx.xxx'
gateway_user: 'root'
gateway_password_file: 'gatewaypassword'
#+ansible_ssh_common_args: '-o ProxyCommand="sshpass -f {{ gateway_password_file }} ssh -l {{ gateway_user }} {{ gateway_address }} -W %h:%p"'
output: collectdata
collect_sosreport: false
sosreport_prefix: ''
sosreport_option: '--batch'
sosreport_delete: true
collect_file_max_size: 10485760
collect_files:
  - /etc/redhat-release
collect_cli_commands:
  - { filename: 'ps', command: '/bin/ps -ef' }
